
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:performance
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
            exec:
              command: 
                - /bin/sh
                - -c 
                - nc -z localhost 8080
            initialDelaySeconds: 60
            periodSeconds: 10
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        resources:
          requests: 
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 500m
