apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql-deployment
spec:
  selector:
    matchLabels:
      app: my-sql-deployment
  template:
    metadata:
      labels:
        app: my-sql-deployment
    spec:
      containers:
      - name: my-sql-deployment
        image: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-password
                name: mysql-db-password